"""Patch EconomyNameKoData.inc with improved lookups for previously unmapped items."""
from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location(
    "fetch", ROOT / "scripts" / "fetch-poe2db-ko-names.py"
)
fetch = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fetch)

INC = ROOT / "src/core/poeninja/EconomyNameKoData.inc"


def read_mapped_keys(text: str) -> set[str]:
    return set(re.findall(r'QStringLiteral\("([^"]+)"\), QStringLiteral', text))


def write_inc(mappings: dict[str, str]) -> None:
    lines = [
        "// Auto-generated by scripts/fetch-poe2db-ko-names.py — do not hand-edit.",
        "// Source: https://poe2db.tw/kr/",
    ]
    for composite in sorted(mappings):
        ko = fetch.cpp_escape(mappings[composite])
        key = fetch.cpp_escape(composite)
        lines.append(
            '        {QStringLiteral("' + key + '"), QStringLiteral("' + ko + '")},'
        )
    INC.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    text = INC.read_text(encoding="utf-8")
    mappings: dict[str, str] = {}
    for key, ko in re.findall(
        r'QStringLiteral\("([^"]+)"\), QStringLiteral\("([^"]*)"\)', text
    ):
        mappings[key] = ko

    items = fetch.load_items()
    cache: dict[str, str | None] = {}
    added = 0
    for category_id, api_id, english_name in items:
        composite = f"{category_id}:{api_id}"
        if composite in mappings:
            continue
        ko = fetch.resolve_korean_name(english_name, cache, composite)
        if ko:
            mappings[composite] = ko
            added += 1
            print(f"+ {composite} -> {ko}", flush=True)

    write_inc(mappings)
    still = [
        f"{c}:{i} | {n}"
        for c, i, n in items
        if f"{c}:{i}" not in mappings
    ]
    print(f"added {added}, total {len(mappings)}, still unmapped {len(still)}", flush=True)
    for line in still:
        print(line, flush=True)
    if still:
        sys.exit(1)
    print("all items mapped", flush=True)


if __name__ == "__main__":
    main()
